- repo: Shougo/dein.vim
  on_func: dein#

- { repo: rhysd/accelerated-jk, on_map: { n: <Plug> } }

- repo: lambdalisue/suda.vim
  on_event: BufRead
  hook_add: let g:suda_smart_edit = 1

- repo: psliwka/vim-smoothie
  on_func: smoothie#
  hook_add: |
    let g:smoothie_no_default_mappings = v:true

- repo: simnalamburt/vim-mundo
  on_cmd: MundoToggle

- repo: easymotion/vim-easymotion
  on_map: { n: <Plug> }
  hook_source: |
    let g:EasyMotion_do_mapping = 0
    let g:EasyMotion_prompt = 'Jump to → '
    let g:EasyMotion_keys = 'fjdkswbeoavn'
    let g:EasyMotion_smartcase = 1
    let g:EasyMotion_use_smartsign_us = 1

- repo: norcalli/nvim-colorizer.lua
  if: has('nvim-0.4')
  on_ft:
    [
      html,
      css,
      sass,
      scss,
      stylus,
      vim,
      javascript,
      javascriptreact,
      typescript,
      typescriptreact,
    ]
  hook_source: |
    lua << EOF
      require 'colorizer'.setup {
        css = { rgb_fn = true; };
        scss = { rgb_fn = true; };
        sass = { rgb_fn = true; };
        stylus = { rgb_fn = true; };
        vim = { names = false; };
        tmux = { names = false; };
        'javascript';
        'javascriptreact';
        'typescript';
        'typescriptreact';
        html = {
          mode = 'foreground';
        }
      }
    EOF

- repo: luochen1990/rainbow
  on_ft:
    [
      html,
      css,
      javascript,
      javascriptreact,
      go,
      python,
      lua,
      rust,
      vim,
      less,
      stylus,
      sass,
      scss,
      json,
      ruby,
      toml,
    ]
  hook_source: let g:rainbow_active = 1
