- repo: HerringtonDarkholme/yats.vim
  on_ft: [typescript, typescriptreact]
  hook_source: |
    call coc#add_extension('coc-tsserver','coc-eslint', 'coc-prettier', 'coc-tslint-plugin' ,'coc-docthis')

- { repo: MaxMEllon/vim-jsx-pretty, on_ft: [javascriptreact, typescriptreact] }

- repo: rust-lang/rust.vim
  on_ft: rust
  hook_source: |
    call coc#add_extension('coc-rust-analyzer')

- { repo: hardcoreplayers/go-nvim, on_ft: [ go, gomod ] }

- repo: ekalinin/Dockerfile.vim
  on_ft: [Dockerfile, docker-compose]
  hook_source: |
    call initself#lsp_init('docker')
