- repo: kana/vim-operator-user

- repo: junegunn/vim-easy-align
  on_cmd: EasyAlign
  hook_add: |
    xmap ga <plug>(easyalign)
    nmap ga <plug>(easyalign)

- repo: kana/vim-operator-replace
  on_map: { vnx: <Plug> }

- repo: machakann/vim-sandwich
  on_map: { vonx: <Plug>(operator-sandwich- }
  hook_add: |
    let g:sandwich_no_default_key_mappings = 1
    let g:operator_sandwich_no_default_key_mappings = 1
    let g:textobj_sandwich_no_default_key_mappings = 1

- repo: kana/vim-textobj-user

- repo: AndrewRadev/splitjoin.vim
  on_map: { n: <Plug>Splitjoin }
  hook_add: |
    let g:splitjoin_join_mapping = ''
    let g:splitjoin_split_mapping = ''

- repo: AndrewRadev/dsf.vim
  on_map: { n: <Plug>Dsf }
  hook_add: let g:dsf_no_mappings = 1

- repo: kana/vim-niceblock
  on_map: { x: <Plug> }

- repo: kana/vim-textobj-function
  on_map: { ox: <Plug> }

- repo: kana/vim-smartchr
  on_event: InsertCharPre
  hook_add: |
    inoremap <expr> , smartchr#one_of(',', ',')
    autocmd FileType go inoremap <buffer><expr> ;
            \ smartchr#loop(':=',';')
    autocmd FileType go inoremap <buffer> <expr> .
          \ smartchr#loop('.', '<-', '->','...')
    autocmd FileType typescript,typescriptreact inoremap <buffer><expr>;
            \ smartchr#loop(':',';')
