- repo: kana/vim-operator-user

- repo: junegunn/vim-easy-align
  on_cmd: EasyAlign
  hook_add: |
    xmap ga <plug>(easyalign)
    nmap ga <plug>(easyalign)

- repo: kana/vim-operator-replace
  on_map: { vnx: <Plug> }
  hook_add: |
    xmap p <Plug>(operator-replace)

- repo: machakann/vim-sandwich
  on_map: { vonx: <Plug>(operator-sandwich- }
  hook_add: |
    let g:sandwich_no_default_key_mappings = 1
    let g:operator_sandwich_no_default_key_mappings = 1
    let g:textobj_sandwich_no_default_key_mappings = 1
    nmap <silent> sa <Plug>(operator-sandwich-add)
    xmap <silent> sa <Plug>(operator-sandwich-add)
    omap <silent> sa <Plug>(operator-sandwich-g@)
    nmap <silent> sd <Plug>(operator-sandwich-delete)<Plug>(operator-sandwich-release-count)<Plug>(textobj-sandwich-query-a)
    xmap <silent> sd <Plug>(operator-sandwich-delete)
    nmap <silent> sr <Plug>(operator-sandwich-replace)<Plug>(operator-sandwich-release-count)<Plug>(textobj-sandwich-query-a)  xmap <silent> sr <Plug>(operator-sandwich-replace)
    nmap <silent> sdb <Plug>(operator-sandwich-delete)<Plug>(operator-sandwich-release-count)<Plug>(textobj-sandwich-auto-a)
    nmap <silent> srb <Plug>(operator-sandwich-replace)<Plug>(operator-sandwich-release-count)<Plug>(textobj-sandwich-auto-a)
    omap ib <Plug>(textobj-sandwich-auto-i)
    xmap ib <Plug>(textobj-sandwich-auto-i)
    omap ab <Plug>(textobj-sandwich-auto-a)
    xmap ab <Plug>(textobj-sandwich-auto-a)
    omap is <Plug>(textobj-sandwich-query-i)
    xmap is <Plug>(textobj-sandwich-query-i)
    omap as <Plug>(textobj-sandwich-query-a)
    xmap as <Plug>(textobj-sandwich-query-a)


- repo: kana/vim-textobj-user

- repo: AndrewRadev/splitjoin.vim
  on_map: { n: <Plug>Splitjoin }
  hook_add: |
    let g:splitjoin_join_mapping = ''
    let g:splitjoin_split_mapping = ''

- repo: AndrewRadev/dsf.vim
  on_map: { n: <Plug>Dsf }
  hook_add: let g:dsf_no_mappings = 1

- repo: kana/vim-niceblock
  on_map: { x: <Plug> }
  hook_add: |
    xmap I  <Plug>(niceblock-I)
    xmap A  <Plug>(niceblock-A)

- repo: kana/vim-textobj-function
  on_map: { ox: <Plug> }
  hook_add: |
    let g:textobj_function_no_default_key_mappings = 1
    omap <silent> af <Plug>(textobj-function-a)
    omap <silent> if <Plug>(textobj-function-i)
    xmap <silent> af <Plug>(textobj-function-a)
    xmap <silent> if <Plug>(textobj-function-i)

- repo: kana/vim-smartchr
  on_event: InsertCharPre
  hook_add: |
    inoremap <expr> , smartchr#one_of(',', ',')
    autocmd FileType go inoremap <buffer><expr> ;
            \ smartchr#loop(':=',';')
    autocmd FileType go inoremap <buffer> <expr> .
          \ smartchr#loop('.', '<-', '->','...')
    autocmd FileType typescript,typescriptreact inoremap <buffer><expr>;
            \ smartchr#loop(':',';')
