- repo: rhysd/committia.vim
  on_path: [COMMIT_EDITMSG, MERGE_MSG]
  hook_source: let g:committia_min_window_width = 7
  hook_add: |
    let g:committia_hooks = {}
    function! g:committia_hooks.edit_open(info)
      imap <buffer><C-d> <Plug>(committia-scroll-diff-down-half)
      imap <buffer><C-u> <Plug>(committia-scroll-diff-up-half)
      setlocal winminheight=1 winheight=1
      resize 10
      startinsert
    endfunction

