[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'lifepillar/vim-gruvbox8'
hook_add = '''
let g:gruvbox_filetype_hi_groups = 1
let g:gruvbox_plugin_hi_groups = 1
'''

#[[plugins]]
#repo = 'morhetz/gruvbox'
#hook_add = '''
#let g:gruvbox_contrast_dark = 'hard'
#'''

[[plugins]]
repo = 'itchyny/lightline.vim'
depends = 'vim-devicons'
hook_add='source ~/.config/nvim/rc/plugins/lightline.vim'

[[plugins]]
repo = 'mengelbrecht/lightline-bufferline'
hook_add='source ~/.config/nvim/rc/plugins/lightline.vim'


[[plugins]]
repo = 'honza/vim-snippets'

[[plugins]]
repo = 'neoclide/coc.nvim'
merge = 0
build = 'yarn install --frozen-lockfile'
hook_add = 'source ~/.config/nvim/rc/plugins/coc.vim'
hook_source = '''
'''

#[[plugins]]
#repo = 'bling/vim-airline'
#hook_add='source ~/.config/nvim/rc/plugins/vim-airline.vim'

#[[plugins]]
#repo = 'vim-airline/vim-airline-themes'
#hook_add = '''
#let g:airline_theme='wombat'
#'''
