#!/usr/bin/env sh

# global settings
yabai -m config mouse_follows_focus             off
yabai -m config focus_follows_mouse             off
yabai -m config window_placement                second_child
yabai -m config window_topmost                  on
yabai -m config window_shadow                   float
yabai -m config window_opacity                  off
yabai -m config split_ratio                     0.50
yabai -m config auto_balance                    on
yabai -m config mouse_modifier                  fn
yabai -m config mouse_action1                   move
yabai -m config mouse_action2                   resize

# border
yabai -m config window_border                   on
yabai -m config window_border_width             5
yabai -m config active_window_border_color      0xff8787af
yabai -m config normal_window_border_color      0xff555555
yabai -m config insert_feedback_color           0xffd75f5f

# general space settings
yabai -m config layout                          bsp
yabai -m config top_padding                     10
yabai -m config bottom_padding                  10
yabai -m config left_padding                    12
yabai -m config right_padding                   12
yabai -m config window_gap                      10

# specific space settings
yabai -m config --space 2 layout             stack
yabai -m config --space 7 layout             float


# window rules
yabai -m rule --add app="^Mail$"                space=2
yabai -m rule --add app="^Chrome$"              space=2
yabai -m rule --add app="^Safari$"              space=3
yabai -m rule --add app="^QQ$"                  manage=off
yabai -m rule --add app="^WeChat$"              manage=off
yabai -m rule --add app="^System Preferences$"  manage=off
yabai -m rule --add app="^licecap$"             manage=off
yabai -m rule --add app="^Finder$"              manage=off

sudo yabai --load-sa
